// GlobalUsings.cs
global using BN.PROJECT.NotificationService;
global using BN.PROJECT.Core;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.OpenApi.Models;
global using Newtonsoft.Json;
global using NuGet.Protocol;
global using Quartz;
global using Serilog;
global using System.ComponentModel.DataAnnotations;
global using System.ComponentModel.DataAnnotations.Schema;
global using System.Net.Http.Headers;
global using System.Text;
global using System.Collections.Concurrent;
global using Microsoft.AspNetCore.SignalR;
global using StackExchange.Redis;
global using Confluent.Kafka;
global using Confluent.Kafka.Admin;
