// <auto-generated />
using System;
using BN.TRADER.AlpacaService;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BN.TRADER.AlpacaService.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240812125834_bars_symbol_added")]
    partial class bars_symbol_added
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BN.TRADER.AlpacaService.AlpacaAsset", b =>
                {
                    b.Property<Guid>("AssetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AssetId");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("BN.TRADER.AlpacaService.AlpacaBar", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("C")
                        .HasColumnType("numeric");

                    b.Property<decimal>("H")
                        .HasColumnType("numeric");

                    b.Property<decimal>("L")
                        .HasColumnType("numeric");

                    b.Property<decimal>("N")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("O")
                        .HasColumnType("numeric");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("T")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("V")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Vw")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Bars");
                });
#pragma warning restore 612, 618
        }
    }
}
