using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace BN.PROJECT.AlpacaService.Migrations
{
    /// <inheritdoc />
    public partial class cleanup_26_9_2 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Bars table was deleted manually outside of migrations; recreate it if missing.
            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS "Bars" (
                    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
                    "Symbol" text NOT NULL,
                    "C" numeric NOT NULL,
                    "H" numeric NOT NULL,
                    "L" numeric NOT NULL,
                    "N" numeric(20,0) NOT NULL,
                    "O" numeric NOT NULL,
                    "T" timestamp with time zone NOT NULL,
                    "V" numeric NOT NULL,
                    "Vw" numeric NOT NULL,
                    CONSTRAINT "PK_Bars" PRIMARY KEY ("Id")
                );
                """);

            migrationBuilder.CreateIndex(
                name: "IX_Bars_Symbol_T",
                table: "Bars",
                columns: new[] { "Symbol", "T" },
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_Bars_Symbol_T",
                table: "Bars");
        }
    }
}
