name: CI/CD Pipeline

on:
  workflow_dispatch:
      inputs:
        service:
          description: 'The service to build and deploy'
          required: true
          default: 'identity'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Get short SHA
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: Build and push IdentityService image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: IdentityService/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/identityservice:latest

    - name: Build and push AlpacaService image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: AlpacaService/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/alpacaserviceservice:latest
