name: Docker Image CI

on:
  workflow_dispatch:
      inputs:
        service:
          description: 'The service to build and deploy'
          required: true
          default: 'identity'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Debug Logging
      run: |
        echo "Starting the build process..."
        echo $(pwd)
     
       
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag identityservice:$(date +%s)
