name: CI/CD Pipeline

on:
  workflow_dispatch:
    inputs:
      service:
        description: 'The service to build and deploy'
        required: true
        default: 'identity'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Get short SHA
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ${{ github.event.inputs.service }}/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.inputs.service }}:latest,${{ secrets.DOCKER_USERNAME }}/${{ github.event.inputs.service }}:${{ steps.vars.outputs.sha_short }}

