name: Build and Push Docker Image

on:
  workflow_dispatch:
      inputs:
        service:
          description: 'The service to build and deploy'
          required: true
          default: 'identity'
  push:
    branches:
      - main
    paths:
      - 'identityservice/**' # Trigger only when Identity Service files are updated

jobs:
  build-and-push:
    runs-on: ubuntu-latest # Use GitHub-hosted runner
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Debug Logging
        run: echo "Starting the build process..."

      # Step 2: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo $GITHUB_TOKEN | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Step 3: Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/identity-service:latest identityservice

      # Step 4: Push the Docker image to GitHub Container Registry
      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ github.repository }}/identity-service:latest
